#!/usr/bin/env python3

from yome import Session
from yome.load import load_knowledgebase
from yome.util import apply_keyword

import pandas as pd
from os.path import dirname, realpath, join
import re
from cobrame.io.jsonme import load_json_me

directory = realpath(dirname(__file__))

me = load_json_me(join(directory, 'iJL1678b_benchmark.json'))
locus_tags = {
    match.group(1) for match in
    (re.search(r'(b\d{4})\b', met.id) for met in me.metabolites)
    if match is not None
}

df = pd.DataFrame([{
    'locus_tag': l,
    'name': l,
    'annotation_quality': 'high',
    'synonyms': [],
} for l in locus_tags])

# Load knowledgebase
session = Session()
load_knowledgebase(session, df, 'iJL1678b',
                   locus_id_column='locus_tag',
                   primary_name_column='name',
                   synonyms_column='synonyms',
                   feature_columns=[],
                   annotation_quality_column='annotation_quality')
session.close()

print()
print('iJL1678b')
print(df.annotation_quality.value_counts())
