#!/usr/bin/env python3

from yome import Session
from yome.load import load_knowledgebase
from yome.util import apply_keyword, html_to_text

import pandas as pd
import json
from os.path import dirname, realpath, join
import re
import gzip

directory = realpath(dirname(__file__))

# Create dataframe from knowledgebase
with gzip.open(join(directory, 'results.json.gz'), 'rt') as f:
    results = json.load(f)
df = pd.DataFrame(results).rename(columns={'b_number': 'locus_tag'})

# Strip columns
df['name'] = df['name'].str.strip()
df.locus_tag = df.locus_tag.str.strip()

# If the b-number wound up as the name, then fix that
# e.g. https://ecocyc.org/gene?orgid=ECOLI&id=G6272
def fix_locus_tag(row):
    name = row['name'].strip()
    if pd.isnull(row.locus_tag) and re.match(r'b\d{4}', name):
        return name
    else:
        return row['locus_tag']
df.locus_tag = df.apply(fix_locus_tag, axis=1)

# Strip tags from summary
df.summary_html = df.summary_html.apply(html_to_text)

# Make sure evidence_html is a string, and strip tags. This is important because
# there are some cases where the wrong value is listed in an alt attribute,
# e.g. alt="Inferred from experiment"
df.evidence_html = df.evidence_html.apply(lambda x: html_to_text(x) if not pd.isnull(x) else None)
df.component_html = df.component_html.apply(lambda x: html_to_text(x) if not pd.isnull(x) else None)

# # Import manual annotations
# man = pd.read_table(join(directory, 'manual_genes.tsv'), sep='\t')
# man_high = man[man.new_ann_quality == 'high']
# man_low = man[man.new_ann_quality == 'low']

# # Make sure there are no invalid ann qualities
# assert(len(man_high) + len(man_low) == len(man))

# Add annotation_quality
df.loc[:, 'annotation_quality'] = 'tbd'

# The following annotation methods override each other, so they go from least to
# most important

# Define keywords
low_keywords_description = [
    'possibly', 'predicted', 'hypothetical', 'putative', 'conserved',
    'uncharacterized protein',
]
# don't use: 'family protein' (see mrdB)

low_keywords_summary = [
    'No information about this',
]

high_keywords_evidence = [
    'assay',
    'traceable author statement to experimental support',
    'reaction blocked in mutant',
]
# Don't use: ['inferred from mutant phenotype', 'inferred from experiment',
#             'inferred from expression pattern', 'gene expression analysis',
#             'inferred by functional complementation', 'binding of purified proteins']
# See Categories notebook

# Genes with complexes are high
df.loc[~df.component_html.isnull(), 'annotation_quality'] = 'high'

# Genes with reaction_equation
df.loc[~df.reaction_equation.isnull(), 'annotation_quality'] = 'high'

# Genes with EC number are high
df.loc[~df.ec_number.isnull(), 'annotation_quality'] = 'high'

# Apply keyword annotations; description
for keyword in low_keywords_description:
    apply_keyword(df, keyword, 'description', False)

# Apply keyword annotations; summary
for keyword in low_keywords_summary:
    apply_keyword(df, keyword, 'summary_html', False)

# Apply keyword annotations; evidence
for keyword in high_keywords_evidence:
    apply_keyword(df, keyword, 'evidence_html', True)

# Phantom genes and pseudogenes are excluded from y-ome description
df.loc[df.is_phantom_gene | df.is_pseudogene, 'annotation_quality'] = 'excluded'

# Insertion elements are high
df['is_insertion_element'] = df.name.str.startswith('ins')
df.loc[df.is_insertion_element, 'annotation_quality'] = 'high'

# # Warn for genes that have automated & manual annotations
# print('The following have automated and manual annotations')
# auto_and_manual = df[(df.annotation_quality != 'tbd')
#                      & (df.locus_tag.isin(man.locus_tag))]
# print(', '.join(f'{locus_tag}/{name} ({annotation_quality}/{man[man.locus_tag == locus_tag].new_ann_quality.iloc[0]})'
#                 for locus_tag, name, annotation_quality in
#                 auto_and_manual[['locus_tag', 'name', 'annotation_quality']].itertuples(index=False)))
# print()

# Apply manual annotations
# df.loc[df.locus_tag.isin(man_high.locus_tag), 'annotation_quality'] = 'high'
# df.loc[df.locus_tag.isin(man_low.locus_tag), 'annotation_quality'] = 'low'

# Pseudogenes and phantom genes to string type
def bool_to_str(val): return 't' if val else 'f'
df.is_pseudogene = df.is_pseudogene.map(bool_to_str)
df.is_phantom_gene = df.is_phantom_gene.map(bool_to_str)
df.is_insertion_element = df.is_insertion_element.map(bool_to_str)

# Load knowledgebase
session = Session()
load_knowledgebase(session, df, 'EcoCyc',
                   locus_id_column='locus_tag',
                   primary_name_column='name',
                   synonyms_column='synonyms',
                   feature_columns=['description', 'summary_html',
                                    'product_type', 'ec_number',
                                    'reaction_equation', 'is_pseudogene',
                                    'is_phantom_gene', 'evidence_html',
                                    'component_html', 'is_insertion_element'],
                   annotation_quality_column='annotation_quality')
session.close()

print()
print('EcoCyc')
print(df.annotation_quality.value_counts())
