#!/usr/bin/env python3

from yome import Session
from yome.load import load_knowledgebase
from yome.util import apply_keyword

from Bio import SeqIO
import pandas as pd
import json
from os.path import dirname, realpath, join
import re
import numpy as np
import gzip

directory = realpath(dirname(__file__))

# Read genbank file
with gzip.open(join(directory, 'NC_000913.3.gb.gz'), 'rt') as f:
    gb_file = SeqIO.read(f, 'gb')

data_list = []
for feature in gb_file.features:
    d = {}

    # only read in CDSs
    if feature.type != 'CDS':
        continue

    d['locus_tag'] = feature.qualifiers['locus_tag'][0]
    d['name'] = feature.qualifiers['gene'][0]
    d['synonyms'] = [x.strip() for x in
                     feature.qualifiers['gene_synonym'][0].split(';')]
    ec_number_list = feature.qualifiers.get('EC_number', None)
    d['ec_numbers'] = None if ec_number_list is None else ','.join(ec_number_list)
    d['product'] = feature.qualifiers.get('product', [None])[0]
    d['function'] = feature.qualifiers.get('function', [None])[0]

    data_list.append(d)

df = pd.DataFrame(data_list)

# Add annotation_quality
df['annotation_quality'] = 'tbd'

# Load knowledgebase
session = Session()
load_knowledgebase(session, df, 'RefSeq',
                   locus_id_column='locus_tag',
                   primary_name_column='name',
                   synonyms_column='synonyms',
                   feature_columns=['ec_numbers', 'product', 'function'],
                   annotation_quality_column='annotation_quality')
session.close()

print()
print('RefSeq')
print(df.annotation_quality.value_counts())
