#!/usr/bin/env python3

from yome import Session
from yome.load import load_knowledgebase
from yome.util import apply_keyword

from Bio import SeqIO
import pandas as pd
import json
from os.path import dirname, realpath, join
import re
import numpy as np

directory = realpath(dirname(__file__))

# Read genbank file
with open(join(directory, 'NC_000913.3.gb'), 'r') as f:
    gb_file = SeqIO.read(f, 'gb')

data_list = []
for feature in gb_file.features:
    d = {}

    # only read in CDSs
    if feature.type != 'CDS':
        continue

    d['locus_tag'] = feature.qualifiers['locus_tag'][0]
    d['name'] = feature.qualifiers['gene'][0]
    d['synonyms'] = [x.strip() for x in
                     feature.qualifiers['gene_synonym'][0].split(';')]

    # TODO pseudogenes, ec numbers, etc
    data_list.append(d)

df = pd.DataFrame(data_list)

from IPython import embed; embed()
import sys; sys.exit()

# Load knowledgebase
session = Session()
load_knowledgebase(session, df, 'RefSeq',
                   locus_id_column='locus_tag',
                   primary_name_column='name',
                   synonyms_column='synonyms',
                   feature_columns=[],
                   annotation_quality_column='annotation_quality')
session.close()

print()
print('EcoCyc')
print(df.annotation_quality.value_counts())
