#!/usr/bin/env python3

from yome import Session
from yome.load import load_knowledgebase
from yome.util import apply_keyword, html_to_text
from yome.models import *

import pandas as pd
import json
from os.path import dirname, realpath, join
import re

directory = realpath(dirname(__file__))
df = pd.read_table(join(directory, 'manual.tsv'), sep='\t', header=0)

session = Session()
load_knowledgebase(session, df, 'Manual',
                   locus_id_column='locus_tag',
                   feature_columns=['notes'],
                   annotation_quality_column='annotation_quality')
session.close()

print()
print('manual')
print(df.annotation_quality.value_counts())
